### ISSUE TITLE
Playing nice with PCO::Replica

### ISSUE THREAD

**Issue by bweave** [seven1m/sidekiq-clutch#1]
Currently, there's not a way to get batched jobs to `read_from_replica` per the [Sidekiq docs in `PCO::Replica`](https://github.com/ministrycentered/pco-replica#sidekiq) because `JobWrapper` is in play. What's the best way to get the two playing nicely together? Here's a couple of ideas that @jbarrieault and I came up with. Thoughts?

1. Patch it and cross your fingers?
```
module Sidekiq
  class Clutch
    class JobWrapper
      include Sidekiq::Worker
      read_from_replica
    end
  end
end
```

![eww](https://user-images.githubusercontent.com/6437945/53027231-8bcd2f80-3432-11e9-89a6-19adc4e8e1bc.gif)
![you-need-jesus](https://user-images.githubusercontent.com/6437945/53027240-8ff94d00-3432-11e9-85ec-e0ffb2271239.gif)

----

2. We could update the docs to recommend using `PCO::Replica`'s **ActiveRecord::Base API** within the job:

```
class MyJob
  include Sidekiq::Worker
  include Sidekiq::Clutch::Worker

  def perform
    Person.read_from_replica do
      #...
    end
  end
end
```

----

3. `PCO::Replica` checks `read_from_replica?` [here](https://github.com/ministrycentered/pco-replica/blob/master/lib/pco/replica/sidekiq/middleware/server.rb#L52), so maybe some kind of delegation to the wrapped class could work? 

```
module Sidekiq
  class Clutch
    class JobWrapper
      def read_from_replica?
        wrapped_class.read_from_replica?
      end
    end
  end
end
```

**Comment by jbarrieault** [comment]
Paper-trail: addressing in [ `pco-replica`](https://github.com/ministrycentered/pco-replica/pull/4)
